// catalogo-data.js
// Datos centrales del catalogo.

const data = [
  // AMIGURUMIS: munecos y personajes tejidos a mano.
  {
    id: 1,
    nombre: "Amigurumi Ariel",
    precio: 85.0,
    categoria: "amigurumis",
    imagen: "media/imagenes/AMIGURUMIS/Ariel.jpg",
    descripcion: "Sirena tejida a mano con detalles suaves y acabado delicado.",
  },
  {
    id: 2,
    nombre: "Amigurumi Boo y Sulivan",
    precio: 120.0,
    categoria: "amigurumis",
    imagen: "media/imagenes/AMIGURUMIS/Boo y Sulivan.jpg",
    descripcion: "Duo tierno tejido a mano, ideal para regalar o coleccionar.",
  },
  {
    id: 3,
    nombre: "Canasta de Conejita",
    precio: 50.0,
    categoria: "amigurumis",
    imagen: "media/imagenes/AMIGURUMIS/Canasta de Conejita.jpeg",
    descripcion: "Canasta artesanal con conejita tejida y detalles decorativos.",
  },
  {
    id: 4,
    nombre: "Amigurumi Capibara",
    precio: 35.0,
    categoria: "amigurumis",
    imagen: "media/imagenes/AMIGURUMIS/Capibara.jpg",
    descripcion: "Capibara tejida a mano con estilo dulce y compacto.",
  },
  {
    id: 5,
    nombre: "Conejita Alegre",
    precio: 45.0,
    categoria: "amigurumis",
    imagen: "media/imagenes/AMIGURUMIS/Conejita Alegre.jpg",
    descripcion: "Conejita tejida con expresion alegre y detalles coloridos.",
  },
  {
    id: 6,
    nombre: "Conejita con Bolso",
    precio: 50.0,
    categoria: "amigurumis",
    imagen: "media/imagenes/AMIGURUMIS/Conejita con Bolso.jpg",
    descripcion: "Conejita artesanal con bolso, lista para un regalo especial.",
  },
  {
    id: 7,
    nombre: "Conejita con Sombrero",
    precio: 45.0,
    categoria: "amigurumis",
    imagen: "media/imagenes/AMIGURUMIS/Conejita con Sombrero.jpg",
    descripcion: "Conejita tejida con sombrero y acabado delicado.",
  },
  {
    id: 8,
    nombre: "Amigurumi Dooby",
    precio: 35.0,
    categoria: "amigurumis",
    imagen: "media/imagenes/AMIGURUMIS/Dooby.jpg",
    descripcion: "Personaje tejido a mano con forma tierna y expresiva.",
  },
  {
    id: 9,
    nombre: "Amigurumi La Bella y La Bestia",
    precio: 150.0,
    categoria: "amigurumis",
    imagen: "media/imagenes/AMIGURUMIS/La Bella y La Bestia.jpg",
    descripcion: "Pareja tejida a mano, perfecta para un regalo romantico.",
  },
  {
    id: 10,
    nombre: "Amigurumi Mafalda",
    precio: 70.0,
    categoria: "amigurumis",
    imagen: "media/imagenes/AMIGURUMIS/Mafalda.jpeg",
    descripcion: "Figura tejida inspirada en Mafalda, con detalles de personaje.",
  },
  {
    id: 11,
    nombre: "Amigurumi Rapunzel y Pascal",
    precio: 95.0,
    categoria: "amigurumis",
    imagen: "media/imagenes/AMIGURUMIS/Rapunzel y Pascal.jpg",
    descripcion: "Rapunzel tejida con Pascal, llena de color y encanto.",
  },
  {
    id: 12,
    nombre: "Amigurumi Vaquita",
    precio: 40.0,
    categoria: "amigurumis",
    imagen: "media/imagenes/AMIGURUMIS/Vaquita.jpg",
    descripcion: "Vaquita tejida a mano, suave y de aspecto adorable.",
  },

  // LLAVEROS: piezas pequenas pensadas para uso diario.
  {
    id: 13,
    nombre: "Llavero Jirafa",
    precio: 18.0,
    categoria: "llaveros",
    imagen: "media/imagenes/LLAVEROS/Llavero Jirafa.jpg",
    descripcion: "Llavero tejido de jirafa, practico y lleno de color.",
  },
  {
    id: 14,
    nombre: "Llavero Koala",
    precio: 18.0,
    categoria: "llaveros",
    imagen: "media/imagenes/LLAVEROS/Llavero Koala.jpg",
    descripcion: "Llavero tejido de koala, pequeno y facil de llevar.",
  },
  {
    id: 15,
    nombre: "Llavero Leon",
    precio: 18.0,
    categoria: "llaveros",
    imagen: "media/imagenes/LLAVEROS/Llavero Leon.jpg",
    descripcion: "Llavero de leon tejido a mano con acabado llamativo.",
  },
  {
    id: 16,
    nombre: "Llavero Luna",
    precio: 18.0,
    categoria: "llaveros",
    imagen: "media/imagenes/LLAVEROS/Llavero Luna.jpeg",
    descripcion: "Llavero de luna tejido a mano, delicado y decorativo.",
  },

  // PERSONALIZADOS: figuras y cuadros hechos a pedido.
  {
    id: 17,
    nombre: "Personalizado Abejitas Maya",
    precio: 120.0,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Abejitas Maya.jpg",
    descripcion: "Pareja de abejitas tejidas para un detalle dulce y especial.",
  },
  {
    id: 18,
    nombre: "Cuadro de Amor",
    precio: 130,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Cuadro de Amor.jpeg",
    descripcion: "Cuadro decorativo personalizado con detalle tejido de amor.",
  },
  {
    id: 19,
    nombre: "Cuadro de Ositos Amorosos",
    precio: 100.0,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Cuadro de Ositos Amorosos.jpg",
    descripcion: "Cuadro con ositos tejidos, ideal para un regalo afectuoso.",
  },
  {
    id: 20,
    nombre: "Muñecas Jo",
    precio: 90,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Muñecas Jo.jpg",
    descripcion: "Munecas personalizadas tejidas con detalles de inspiracion. Precio por Unidad",
  },
  {
    id: 21,
    nombre: "Personalizado Alianza Lima",
    precio: 65.0,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Personalizado Alianza Lima.jpeg",
    descripcion: "Figura personalizada con tematica de Alianza Lima.",
  },
  {
    id: 22,
    nombre: "Personalizado Campesino",
    precio: 100.0,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Personalizado Campesino.jpeg",
    descripcion: "Figura campesina personalizada con detalles artesanales.",
  },
  {
    id: 23,
    nombre: "Personalizado Diseñadora",
    precio: 65.0,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Personalizado Diseñadora.jpeg",
    descripcion: "Figura personalizada de disenadora con accesorios tejidos.",
  },
  {
    id: 24,
    nombre: "Personalizado Geisha",
    precio: 100.0,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Personalizado Geisha.jpg",
    descripcion: "Geisha personalizada tejida con vestido y detalles finos.",
  },
  {
    id: 25,
    nombre: "Personalizado Hombre 2",
    precio: 35.0,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Personalizado Hombre 2.jpg",
    descripcion: "Figura masculina personalizada con acabado artesanal.",
  },
  {
    id: 26,
    nombre: "Personalizado Hombre",
    precio: 65.0,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Personalizado Hombre.jpeg",
    descripcion: "Figura de hombre personalizada segun estilo y referencia.",
  },
  {
    id: 27,
    nombre: "Personalizado Mujer 2",
    precio: 110.0,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Personalizado Mujer 2.jpg",
    descripcion: "Figura femenina personalizada con rasgos y colores a pedido.",
  },
  {
    id: 28,
    nombre: "Personalizado Mujer",
    precio: 110.0,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Personalizado Mujer.jpg",
    descripcion: "Figura de mujer tejida a mano y personalizada.",
  },
  {
    id: 29,
    nombre: "Personalizado Obstetra",
    precio: 110.0,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Personalizado Obstetra.jpg",
    descripcion: "Figura profesional personalizada con detalles de obstetra.",
  },
  {
    id: 30,
    nombre: "Personalizado Policia",
    precio: 35.0,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Personalizado Policia.jpg",
    descripcion: "Figura policial personalizada con uniforme tejido.",
  },
  {
    id: 31,
    nombre: "Personalizado Psicologa",
    precio: 65,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Personalizado Psicologa.jpeg",
    descripcion: "Figura profesional personalizada con detalles de psicologa.",
  },
  {
    id: 32,
    nombre: "Personalizado Trabajador",
    precio: 110,
    categoria: "personalizados",
    imagen: "media/imagenes/PERSONALIZADOS/Personalizado Trabajador.jpg",
    descripcion: "Figura de trabajador personalizada con detalles a medida.",
  },

  // RAMOS: flores tejidas, macetas y arreglos tematicos.
  {
    id: 33,
    nombre: "Macetas",
    precio: 35.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Macetas.jpg",
    descripcion: "Macetas tejidas con flores decorativas y acabado artesanal.",
  },
  {
    id: 34,
    nombre: "Ramo Amarillo",
    precio: 60.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Amarillo.jpg",
    descripcion: "Ramo amarillo tejido a mano, alegre y luminoso.",
  },
  {
    id: 35,
    nombre: "Ramo CR7",
    precio: 75.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo CR7.jpg",
    descripcion: "Ramo tematico CR7 con flores tejidas y detalle deportivo.",
  },
  {
    id: 36,
    nombre: "Ramo Girasol",
    precio: 40.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Girasol.jpg",
    descripcion: "Ramo de girasol tejido, ideal para un regalo duradero.",
  },
  {
    id: 37,
    nombre: "Ramo Lirio Rojo",
    precio: 40,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Lirio Rojo.jpg",
    descripcion: "Ramo de lirio rojo tejido con presencia elegante.",
  },
  {
    id: 38,
    nombre: "Ramo Messi",
    precio: 75.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Messi.jpg",
    descripcion: "Ramo tematico Messi con flores tejidas y detalle futbolero.",
  },
  {
    id: 39,
    nombre: "Ramo Muelita",
    precio: 95.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Muelita.jpg",
    descripcion: "Ramo tematico de muelita, dulce y original para regalar.",
  },
  {
    id: 40,
    nombre: "Ramo Personalizado",
    precio: 85.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Personalizado.jpg",
    descripcion: "Ramo tejido a pedido con colores y detalles personalizados.",
  },
  {
    id: 41,
    nombre: "Ramo Pinguinos",
    precio: 60.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Pinguinos.jpg",
    descripcion: "Ramo con pinguinos tejidos, tierno y diferente.",
  },
  {
    id: 42,
    nombre: "Ramo Pooh",
    precio: 110.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Pooh.jpg",
    descripcion: "Ramo tematico Pooh con flores tejidas y toque infantil.",
  },
  {
    id: 43,
    nombre: "Ramo Reversible",
    precio: 40.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Reversible.jpg",
    descripcion: "Ramo reversible tejido con doble encanto visual.",
  },
  {
    id: 44,
    nombre: "Ramo Rosa + Tulipán",
    precio: 55.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Rosa + Tulipán.jpg",
    descripcion: "Combinacion de rosa y tulipan tejido para un detalle fino.",
  },
  {
    id: 45,
    nombre: "Ramo Rosa Morada",
    precio: 35.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Rosa Morada.jpg",
    descripcion: "Ramo de rosa morada tejida, delicado y elegante.",
  },
  {
    id: 46,
    nombre: "Ramo Rosa Roja",
    precio: 15.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Rosa Roja.jpg",
    descripcion: "Ramo de rosa roja tejida, clasico y romantico.",
  },
  {
    id: 47,
    nombre: "Ramo Rosa Rosada",
    precio: 15.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Rosa Rosada.jpg",
    descripcion: "Ramo de rosa rosada tejida, suave y femenino.",
  },
  {
    id: 48,
    nombre: "Ramo Rosas + Margaritas",
    precio: 50.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Rosas + Margaritas.jpg",
    descripcion: "Ramo mixto de rosas y margaritas tejidas a mano.",
  },
  {
    id: 49,
    nombre: "Ramo Snoopy",
    precio: 55.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Snoopy.jpg",
    descripcion: "Ramo Snoopy tejido con flores y detalle tematico.",
  },
  {
    id: 50,
    nombre: "Ramo Tulipán + Margarita",
    precio: 60.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Tulipán + Margarita.jpg",
    descripcion: "Ramo de tulipan y margarita tejido con acabado colorido.",
  },
  {
    id: 51,
    nombre: "Ramo Tulipán + Tulipán Pequeño + Margarita",
    precio: 35.0,
    categoria: "ramos",
    imagen: "media/imagenes/RAMOS FLORES/Ramo Tulipán +Tulipán Pequeño + Margarita.jpg",
    descripcion: "Ramo mixto de tulipanes y margarita tejido a mano.",
  },

  // VIRGENES: figuras religiosas tejidas a mano.
  {
    id: 52,
    nombre: "Virgen de Guadalupe 2",
    precio: 80.0,
    categoria: "virgenes",
    imagen: "media/imagenes/VIRGENES/Virgen de Guadalupe 2.jpg",
    descripcion: "Virgen de Guadalupe tejida con acabado sobrio y delicado.",
  },
  {
    id: 53,
    nombre: "Virgen de Guadalupe con Rosario",
    precio: 95.0,
    categoria: "virgenes",
    imagen: "media/imagenes/VIRGENES/Virgen de Guadalupe con Rosario.jpg",
    descripcion: "Virgen tejida con rosario, ideal para decorar o regalar.",
  },
  {
    id: 54,
    nombre: "Virgen de Guadalupe",
    precio: 80.0,
    categoria: "virgenes",
    imagen: "media/imagenes/VIRGENES/Virgen de Guadalupe.jpg",
    descripcion: "Figura tejida de la Virgen de Guadalupe con detalles finos.",
  },
  {
    id: 55,
    nombre: "Virgen Maria",
    precio: 65.0,
    categoria: "virgenes",
    imagen: "media/imagenes/VIRGENES/Virgen Maria.jpg",
    descripcion: "Virgen Maria tejida a mano, sencilla y devocional.",
  },
];
