// catalogo-data.js
// Datos centrales del catalogo.

const data = [
  { id: 1, nombre: "Amigurumi Ariel", precio: 65.0, categoria: "amigurumis", imagen: "media/imagenes/AMIGURUMIS/Ariel.jpg" },
  { id: 2, nombre: "Amigurumi Bella y Bestia", precio: 80.0, categoria: "amigurumis", imagen: "media/imagenes/AMIGURUMIS/Bella y Bestia.jpg" },
  { id: 3, nombre: "Amigurumi Boo y Sulivan con traje", precio: 78.0, categoria: "amigurumis", imagen: "media/imagenes/AMIGURUMIS/Boo y Sulivan con traje.jpg" },
  { id: 4, nombre: "Amigurumi Boo y Sulivan", precio: 70.0, categoria: "amigurumis", imagen: "media/imagenes/AMIGURUMIS/Boo y Sulivan.jpg" },
  { id: 5, nombre: "Amigurumi Capibara", precio: 55.0, categoria: "amigurumis", imagen: "media/imagenes/AMIGURUMIS/Capibara.jpg" },
  { id: 6, nombre: "Amigurumi Coneja con flor", precio: 58.0, categoria: "amigurumis", imagen: "media/imagenes/AMIGURUMIS/Coneja con flor.jpg" },
  { id: 7, nombre: "Amigurumi Conejo con cartera", precio: 60.0, categoria: "amigurumis", imagen: "media/imagenes/AMIGURUMIS/Conejo con cartera.jpg" },
  { id: 8, nombre: "Amigurumi Conejo con sombrero", precio: 62.0, categoria: "amigurumis", imagen: "media/imagenes/AMIGURUMIS/Conejo con sombrero.jpg" },
  { id: 9, nombre: "Amigurumi Dooby", precio: 50.0, categoria: "amigurumis", imagen: "media/imagenes/AMIGURUMIS/Dooby.jpg" },
  { id: 10, nombre: "Amigurumi Pollo", precio: 52.0, categoria: "amigurumis", imagen: "media/imagenes/AMIGURUMIS/Pollo.jpg" },
  { id: 11, nombre: "Amigurumi Rapunzel", precio: 75.0, categoria: "amigurumis", imagen: "media/imagenes/AMIGURUMIS/Rapunzel.jpg" },
  { id: 12, nombre: "Amigurumi Vaca", precio: 57.0, categoria: "amigurumis", imagen: "media/imagenes/AMIGURUMIS/Vaca.jpg" },

  { id: 13, nombre: "Llavero Jirafa", precio: 15.0, categoria: "llaveros", imagen: "media/imagenes/LLAVEROS/Llavero Jirafa.jpg" },
  { id: 14, nombre: "Llavero Koala", precio: 18.0, categoria: "llaveros", imagen: "media/imagenes/LLAVEROS/Llavero Koala.jpg" },
  { id: 15, nombre: "Llavero Leon", precio: 20.0, categoria: "llaveros", imagen: "media/imagenes/LLAVEROS/Llavero Leon.jpg" },

  { id: 16, nombre: "Personalizado Abejitas Maya", precio: 65.0, categoria: "personalizados", imagen: "media/imagenes/PERSONALIZADOS/Abejitas Maya.jpg" },
  { id: 17, nombre: "Personalizado Geisha", precio: 70.0, categoria: "personalizados", imagen: "media/imagenes/PERSONALIZADOS/Personalizado Geisha.jpg" },
  { id: 18, nombre: "Personalizado Gemelas", precio: 80.0, categoria: "personalizados", imagen: "media/imagenes/PERSONALIZADOS/Personalizado Gemelas.jpg" },
  { id: 19, nombre: "Personalizado Hombre 2", precio: 68.0, categoria: "personalizados", imagen: "media/imagenes/PERSONALIZADOS/Personalizado Hombre 2.jpg" },
  { id: 20, nombre: "Personalizado Hombre", precio: 65.0, categoria: "personalizados", imagen: "media/imagenes/PERSONALIZADOS/Personalizado Hombre.jpg" },
  { id: 21, nombre: "Personalizado Mujer 2", precio: 68.0, categoria: "personalizados", imagen: "media/imagenes/PERSONALIZADOS/Personalizado Mujer 2.jpg" },
  { id: 22, nombre: "Personalizado Mujer", precio: 65.0, categoria: "personalizados", imagen: "media/imagenes/PERSONALIZADOS/Personalizado Mujer.jpg" },
  { id: 23, nombre: "Personalizado Obstetra", precio: 75.0, categoria: "personalizados", imagen: "media/imagenes/PERSONALIZADOS/Personalizado Obstetra.jpg" },
  { id: 24, nombre: "Personalizado Ositos", precio: 72.0, categoria: "personalizados", imagen: "media/imagenes/PERSONALIZADOS/Personalizado Ositos.jpg" },
  { id: 25, nombre: "Personalizado Policia", precio: 75.0, categoria: "personalizados", imagen: "media/imagenes/PERSONALIZADOS/Personalizado Policia.jpg" },
  { id: 26, nombre: "Amigurumi Personalizado", precio: 60.0, categoria: "personalizados", imagen: "media/imagenes/PERSONALIZADOS/Personalizado.jpg" },

  { id: 27, nombre: "Ramo Pinguino", precio: 55.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo  Pinguino.jpg" },
  { id: 28, nombre: "Ramo Amarillo", precio: 50.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Amarillo.jpg" },
  { id: 29, nombre: "Ramo Colorido", precio: 65.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Colorido.jpg" },
  { id: 30, nombre: "Ramo CR7", precio: 75.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo CR7.jpg" },
  { id: 31, nombre: "Ramo Dia de la Madre", precio: 80.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Dia de la Madre.jpg" },
  { id: 32, nombre: "Ramo Flores Rosadas", precio: 58.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Flores Rosadas.jpg" },
  { id: 33, nombre: "Ramo Girasol", precio: 60.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Girasol.jpg" },
  { id: 34, nombre: "Ramo Macetas", precio: 52.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Macetas.jpg" },
  { id: 35, nombre: "Ramo Messi", precio: 75.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Messi.jpg" },
  { id: 36, nombre: "Ramo Muelita", precio: 62.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Muelita.jpg" },
  { id: 37, nombre: "Ramo Pooh", precio: 68.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Pooh.jpg" },
  { id: 38, nombre: "Ramo Reversible", precio: 70.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Reversible.jpg" },
  { id: 39, nombre: "Ramo Rosa Dia de la Madre", precio: 72.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Rosa Dia de la Madre.jpg" },
  { id: 40, nombre: "Ramo Rosa Morada", precio: 58.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Rosa Morada.jpg" },
  { id: 41, nombre: "Ramo Rosa Roja", precio: 60.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Rosa Roja.jpg" },
  { id: 42, nombre: "Ramo Rosa Rosada", precio: 60.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Rosa Rosada.jpg" },
  { id: 43, nombre: "Ramo Rosado", precio: 55.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Rosado.jpg" },
  { id: 44, nombre: "Ramo Snoopy", precio: 68.0, categoria: "ramos", imagen: "media/imagenes/RAMOS FLORES/Ramo Snoopy.jpg" },

  { id: 45, nombre: "Virgen de Guadalupe", precio: 55.0, categoria: "virgenes", imagen: "media/imagenes/VIRGENES/Virgen de Guadalupe 2.jpg" },
  { id: 46, nombre: "Virgen de Guadalupe con Rosario", precio: 65.0, categoria: "virgenes", imagen: "media/imagenes/VIRGENES/Virgen de Guadalupe con Rosario.jpg" },
  { id: 47, nombre: "Virgen de Guadalupe", precio: 55.0, categoria: "virgenes", imagen: "media/imagenes/VIRGENES/Virgen de guadalupe.jpg" },
  { id: 48, nombre: "Virgen Maria", precio: 50.0, categoria: "virgenes", imagen: "media/imagenes/VIRGENES/Virgen Maria.jpg" },
];
